### PR TITLE
Add Excite Funding to Acknowledgments & Add ESOP paper & Team Picture

### PR DESCRIPTION
**Pull request by michael-schwarz**
Does anyone have a copy of Martin Schwarz's dissertation? I can not find it anywhere online, so I had to link to this bookstore that sells it for ~60€...

Closes #428.

### CODE REVIEW

**Comment by sim642** [comment]
> Does anyone have a copy of Martin Schwarz's dissertation? I can not find it anywhere online, so I had to link to this bookstore that sells it for ~60€...

It's already linked on the site: http://www2.in.tum.de/bib/files/diss-schwarz.pdf. Or do you mean something else?

**Comment by sim642** [comment]
Maybe the new team photo should be slightly cropped? Looks a bit odd with all the empty space on the right.

**Comment by michael-schwarz** [comment]
> It's already linked on the site: http://www2.in.tum.de/bib/files/diss-schwarz.pdf. Or do you mean something else?

That link is a 404 though!

**Comment by sim642** [comment]
> That link is a 404 though!

Not for me, I get this PDF from there: [diss-schwarz.pdf](https://github.com/goblint/GobWeb/files/10477905/diss-schwarz.pdf). Maybe there's something funny happening when you try accessing it within TUM networks.

**Comment by michael-schwarz** [comment]
> Maybe there's something funny happening when you try accessing it within TUM networks.

It seems to be some sort of https:// vs http:// shenanigans are happening here. With https:// one gets a 404, without it, it works... I'll ask Michael Petter if he has an idea to fix it.

**Comment by michael-schwarz** [comment]
Michael Petter fixed the webserver, the URLs now all work. There's no need to change these then.

**Review by sim642 — APPROVED** [review]

**Pull request merged**
